### ISSUE TITLE
💚 ci/cd: Flask API BE에 연결

### ISSUE THREAD

**Issue by Daehyun-Bigbread** [Kakao-Groomton-MusicGen/AI-Model#28]
# Title

- Flask API BE에 연결

# TODO

- [x] 음원파일을 벡엔드에 던져주는 식으로 처리 - Music_uploader.py 에서 flask api로 처리
- [x] 연결 자체는 돼 있고 suno base url localhost인거 서버에서 테스트 필요
- [x] app.py와 music_uploader.py 및 전체 프로세스 확인

# etc

- 현재 클라우드와 연결중. 6시간 전에는 이상없었음
